"""first_commit

Revision ID: 3f2f4257a6d9
Revises: 
Create Date: 2023-03-18 14:14:05.303226

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3f2f4257a6d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'documents',
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column('bucket_name', sa.Text(), nullable=False),
        sa.Column('file_name', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('uuid')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
